version: 2
updates:
  - package-ecosystem: cargo
    directory: "/rustytime"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Etc/UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust
    commit-message:
      prefix: deps
      include: scope
    rebase-strategy: auto
    groups:
      rust-runtime:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      rust-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: "Etc/UTC"
    target-branch: "main"
    open-pull-requests-limit: 8
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: deps
      include: scope
    groups:
      frontend-runtime:
        dependency-type: "production"
        patterns:
          - "*"
      frontend-dev:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
      day: wednesday
      time: "06:00"
      timezone: "Etc/UTC"
    target-branch: "main"
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - infra
    commit-message:
      prefix: deps
      include: scope
    groups:
      docker-base-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "06:00"
      timezone: "Etc/UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: deps
      include: scope
    groups:
      actions:
        patterns:
          - "*"
