-- Drop the functions
DROP FUNCTION IF EXISTS calculate_user_duration(INT, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, TEXT, TEXT, TEXT, INT);
DROP FUNCTION IF EXISTS calculate_all_user_durations(TIMESTAMPTZ, TIMESTAMPTZ, INT);
